# Generated by Django 3.1.4 on 2022-05-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0021_diagnosis_diagnosis_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis_report',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
